In [41]:
from finviz.screener import Screener
import nest_asyncio
import datetime as dt
import pandas as pd
import yfinance as yf

nest_asyncio.apply()

filter = ['sh_avgvol_o2000', 'sh_opt_option', 'sh_price_o10', 'sh_short_o30' ]

stock_list = Screener(filters=filter, table='Ownership', order='-shortinterestshare')
#print(stock_list)
stock_df = pd.DataFrame(columns = ['stock', 'price', 'volume', 'float_short'])

print("%s %s %s %s" % ('Ticker', 'Price', 'Volume', 'Float Short'))
for stock in stock_list:
    symbol = stock['Ticker']
    price = stock['Price']
    volume = stock['Volume']
    float_short = stock['Float Short'] 
    
    num_str = float_short.split("%")[0]
    percent = float(num_str) 
    if (percent > 50):
        #print("%s %s %s %s" % (stock['Ticker'], price, volume, float_short))
        stock_df = stock_df.append({'stock': symbol, 'price' : price, 'volume' : volume, 'float_short': float_short}, ignore_index=True)
stock_df.tail(10)

Ticker Price Volume Float Short

   stock   price      volume float_short
1   ATUS   34.18   8,646,363      76.00%
2   FUBO   46.75  58,664,864      75.24%
3     XL   19.49   8,851,032      72.32%
4   GOEV   15.14   5,112,123      66.02%
5   BBBY   52.89  90,316,824      65.72%
6   SPWR   52.34  15,701,445      57.45%
7    MAC   22.38  58,466,592      52.62%
8    SKT   17.86  27,156,630      51.91%
9   TLRY   18.55  37,553,368      51.67%
10   GSX  142.70  32,878,280      50.85%